# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
separator=true
separator_block_width=10

[greetings]
command=echo "HARMONY OR ☆DIE☆"
markup=pango
interval=once

[time]
command=date '+%Y-%m-%d %H:%M:%S'
markup=pango
interval=1

#[battery]
#command=/home/$USER/.config/i3blocks/battery.sh
#interval=10

[shutdown_menu]
full_text= 
markup=pango
command=/home/$USER/.config/i3blocks/shutdown_menu
#FG_COLOR=#bbbbbb
#BG_COLOR=#111111
#HLFG_COLOR=#111111
#HLBG_COLOR=#bbbbbb
#BORDER_COLOR=#222222
#ROFI_TEXT=Menu:
ROFI_OPTIONS=-width 2 -theme arthur
#ZENITY_TITLE=Menu
#ZENITY_TEXT=Action:
#ZENITY_OPTIONS=--column= --hide-header
ENABLE_CONFIRMATIONS=true #(must be true or false)
LAUNCHER=rofi
LOCKSCRIPT=exec /home/$USER/.config/scripts/lock
